# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Verta
    url: https://vertastack.com
assignees: 
  - ngdimitrov

status-website:
  cname: status.example.com
